// The remote page: the live screen, scaled to the window; pointer down/move/up become touches.
static const char PAGE[] =
"<!doctype html><html><head><meta charset=utf-8>"
"<meta name=viewport content=\"width=device-width,initial-scale=1\">"
"<title>MPC Remote</title><style>"
"html,body{margin:0;background:#111;color:#ccc;font-family:system-ui,sans-serif;height:100%}"
".wrap{display:flex;flex-direction:column;height:100%}"
".bar{display:flex;gap:12px;align-items:center;padding:6px 12px;background:#1b1b1b;font-size:13px}"
".sp{flex:1}#st{color:#888}"
"#btns{display:flex;flex-wrap:wrap;gap:6px 14px;padding:6px 12px;background:#161616;align-items:flex-start}"
"#btns .g{display:flex;gap:4px;align-items:center}#btns .g i{font-style:normal;color:#666;font-size:11px;margin-right:2px}"
"#btns button{min-width:44px;background:#2a2a2a;color:#ddd;border:1px solid #444;border-radius:4px;padding:6px 10px;font-size:12px;cursor:pointer;touch-action:none;user-select:none}"
"#btns button.on{background:#47a;border-color:#8af;color:#fff}#btns button.err{background:#733;border-color:#c66}"
"#btns button.lt{border-style:dashed}"
"#lrn{padding:2px 12px 6px;font-size:12px;color:#aaa;display:flex;gap:6px;align-items:center;flex-wrap:wrap;background:#161616}"
"#lrn input{background:#222;color:#ddd;border:1px solid #444;border-radius:4px;padding:4px 6px;width:9em}"
"#lrn button{background:#2a2a2a;color:#ddd;border:1px solid #444;border-radius:4px;padding:4px 10px;cursor:pointer}#lm{color:#9c9}"
"#bmsg{color:#c88;font-size:12px;padding:0 12px;min-height:0}"
".stage{flex:1;display:flex;align-items:center;justify-content:center;overflow:hidden;min-height:0}"
"#s{max-width:100%;max-height:100%;touch-action:none;cursor:crosshair;user-select:none}"
"</style></head><body><div class=wrap>"
"<div class=bar><span id=st></span><span class=sp></span>"
"<label><input type=checkbox id=half> Half resolution (faster)</label></div>"
"<div id=btns></div><div id=bmsg></div>"
"<div id=lrn>Teach a button: <input id=ln placeholder=\"name, e.g. PLAY\" maxlength=20><button id=lb>Learn</button><span id=lm></span></div>"
"<div class=stage><img id=s alt=\"MPC screen\" draggable=false></div>"
"</div><script>"
"var img=document.getElementById('s'),half=document.getElementById('half'),W=1280,H=800;"
"function load(){img.src='/stream?half='+(half.checked?1:0)+'&t='+Date.now();}"
"half.onchange=load;img.onerror=function(){setTimeout(load,2000);};"
"fetch('/info').then(function(r){return r.json();}).then(function(i){"
" if(i.width){W=i.width;H=i.height;}"
" document.getElementById('st').textContent=i.width?(i.width+' x '+i.height+' '+i.format+', touch '+i.touch):i.capture;"
"}).catch(function(){});"
"function P(e){var r=img.getBoundingClientRect();"
" return '?x='+Math.round((e.clientX-r.left)/r.width*W)+'&y='+Math.round((e.clientY-r.top)/r.height*H);}"
"var dn=false,lm=0;"
"img.addEventListener('pointerdown',function(e){e.preventDefault();dn=true;"
" try{img.setPointerCapture(e.pointerId);}catch(_){}fetch('/down'+P(e));});"
"img.addEventListener('pointermove',function(e){if(!dn)return;"
" var t=Date.now();if(t-lm<40)return;lm=t;fetch('/move'+P(e));});"
"function end(){if(!dn)return;dn=false;fetch('/up');}"
"img.addEventListener('pointerup',end);img.addEventListener('pointercancel',end);"
"var GR=[['Transport',['PLAY','STOP','REC']],['Views',['MATRIX','CLIP','MIXER','NOTE','KNOBS','LAUNCH']],"
" ['Navigate',['UP','DOWN','LEFT','RIGHT','MENU']],['Hold (click to latch)',['SHIFT','EDIT','COPY']],"
" ['Other',['MUTE','SOLO','ARM','UNDO','SAVE']]],LT={SHIFT:1,EDIT:1,COPY:1},"
"IC={PLAY:9654,STOP:9632,REC:9679,UP:9650,DOWN:9660,LEFT:9664,RIGHT:9654,UNDO:8630};"
"function bmsg(t){document.getElementById('bmsg').textContent=t||'';}"
"function bsend(n,act,el){fetch('/button?name='+encodeURIComponent(n)+'&action='+act).then(function(r){"
" if(r.ok){bmsg('');return;}return r.text().then(function(t){bmsg(n+': '+t);if(el){el.classList.add('err');"
"  setTimeout(function(){el.classList.remove('err');},1500);}});}).catch(function(){bmsg('The device did not answer.');});}"
"function mk(n){var b=document.createElement('button');b.textContent=(IC[n]?String.fromCharCode(IC[n])+' ':'')+n;b.title=n;"
" if(LT[n]){b.className='lt';var t=0;b.onclick=function(){if(t){clearInterval(t);t=0;b.classList.remove('on');bsend(n,'up',b);}"
"  else{b.classList.add('on');bsend(n,'down',b);t=setInterval(function(){bsend(n,'down',b);},1500);}};return b;}"
" var d=false;function up(e){if(!d)return;d=false;b.classList.remove('on');bsend(n,'up',b);}"
" b.addEventListener('pointerdown',function(e){e.preventDefault();d=true;b.classList.add('on');"
"  try{b.setPointerCapture(e.pointerId);}catch(_){}bsend(n,'down',b);});"
" b.addEventListener('pointerup',up);b.addEventListener('pointercancel',up);b.addEventListener('lostpointercapture',up);return b;}"
"function rows(){fetch('/buttons').then(function(r){return r.json();}).then(function(l){var box=document.getElementById('btns'),seen={};box.innerHTML='';"
" if(!l.length){bmsg('No hardware buttons are known for this device yet (see learn_button in the README).');return;}"
" GR.forEach(function(g){var have=g[1].filter(function(n){return l.indexOf(n)>=0;});if(!have.length)return;"
"  var d=document.createElement('div');d.className='g';var h=document.createElement('i');h.textContent=g[0];d.appendChild(h);"
"  have.forEach(function(n){seen[n]=1;d.appendChild(mk(n));});box.appendChild(d);});"
" var rest=l.filter(function(n){return!seen[n];});if(rest.length){var d=document.createElement('div');d.className='g';"
"  var h=document.createElement('i');h.textContent='Learned';d.appendChild(h);rest.forEach(function(n){d.appendChild(mk(n));});box.appendChild(d);}"
"}).catch(function(){});}rows();"
"var lt=0;document.getElementById('lb').onclick=function(){var n=document.getElementById('ln').value.trim(),m=document.getElementById('lm');"
" if(!n){m.textContent='Type a name first.';return;}if(lt)return;var left=15;m.textContent='Press that button on the device now... '+left+' s';"
" lt=setInterval(function(){left--;if(left>0)m.textContent='Press that button on the device now... '+left+' s';},1000);"
" fetch('/learn?name='+encodeURIComponent(n)+'&timeout=15000').then(function(r){return r.text().then(function(t){clearInterval(lt);lt=0;"
"  m.textContent=t;if(r.ok)rows();});}).catch(function(){clearInterval(lt);lt=0;m.textContent='The device did not answer.';});};"
"load();"
"</script></body></html>";
