// The remote page: the live screen, scaled to the window; pointer down/move/up become touches.
static const char PAGE[] =
"<!doctype html><html><head><meta charset=utf-8>"
"<meta name=viewport content=\"width=device-width,initial-scale=1\">"
"<title>MPC Remote</title><style>"
"html,body{margin:0;background:#111;color:#ccc;font-family:system-ui,sans-serif;height:100%}"
".wrap{display:flex;flex-direction:column;height:100%}"
".bar{display:flex;gap:12px;align-items:center;padding:6px 12px;background:#1b1b1b;font-size:13px}"
".sp{flex:1}#st{color:#888}"
"#btns{display:flex;flex-wrap:wrap;gap:4px;padding:4px 12px;background:#161616}"
"#btns button{background:#2a2a2a;color:#ddd;border:1px solid #444;border-radius:4px;padding:3px 9px;font-size:12px;cursor:pointer}"
"#btns button:active{background:#47a}"
".stage{flex:1;display:flex;align-items:center;justify-content:center;overflow:hidden;min-height:0}"
"#s{max-width:100%;max-height:100%;touch-action:none;cursor:crosshair;user-select:none}"
"</style></head><body><div class=wrap>"
"<div class=bar><span id=st></span><span class=sp></span>"
"<label><input type=checkbox id=half> Half resolution (faster)</label></div>"
"<div id=btns></div>"
"<div class=stage><img id=s alt=\"MPC screen\" draggable=false></div>"
"</div><script>"
"var img=document.getElementById('s'),half=document.getElementById('half'),W=1280,H=800;"
"function load(){img.src='/stream?half='+(half.checked?1:0)+'&t='+Date.now();}"
"half.onchange=load;"
"fetch('/info').then(function(r){return r.json();}).then(function(i){"
" if(i.width){W=i.width;H=i.height;}"
" document.getElementById('st').textContent=i.width?(i.width+' x '+i.height+' '+i.format+', touch '+i.touch):i.capture;"
"}).catch(function(){});"
"function P(e){var r=img.getBoundingClientRect();"
" return '?x='+Math.round((e.clientX-r.left)/r.width*W)+'&y='+Math.round((e.clientY-r.top)/r.height*H);}"
"var dn=false,lm=0;"
"img.addEventListener('pointerdown',function(e){e.preventDefault();dn=true;"
" try{img.setPointerCapture(e.pointerId);}catch(_){}fetch('/down'+P(e));});"
"img.addEventListener('pointermove',function(e){if(!dn)return;"
" var t=Date.now();if(t-lm<40)return;lm=t;fetch('/move'+P(e));});"
"function end(){if(!dn)return;dn=false;fetch('/up');}"
"img.addEventListener('pointerup',end);img.addEventListener('pointercancel',end);"
"fetch('/buttons').then(function(r){return r.json();}).then(function(l){var d=document.getElementById('btns');"
" l.forEach(function(n){var b=document.createElement('button');b.textContent=n;"
"  b.onclick=function(){fetch('/button?name='+encodeURIComponent(n));};d.appendChild(b);});}).catch(function(){});"
"load();"
"</script></body></html>";
